version: '3'
services:
  docker:
    image: postgres:11.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

  app:
    build: .
    depends_on:
      - docker
    ports:
      - 5000:5000
    environment:
      DEBUG: '1'
      JSON_AS_ASCII: '0'
      SECRET_KEY: '\xf7\xf4\x9bb\xd7\xa8\xdb\xee\x9f\xe3\x98SR\xda\xb0@\xb7\x12\xa4uB\xda\xa3\x1b'
      STRIPE_API_KEY: ''
      SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://postgres:postgres@docker:5432/sample'
      SQLALCHEMY_ECHO: '1'
      SQLALCHEMY_POOL_SIZE: '5'
      SQLALCHEMY_MAX_OVERFLOW: '10'
      SQLALCHEMY_POOL_TIMEOUT: '30'
      SQLALCHEMY_TRACK_MODIFICATIONS: '0'
